# -*- coding: utf-8 -*-
"""week3_abhishek_rajauria_jecrc_university.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcUFtag1ZRLvDL2Q_B50r7vSDCP-ODhD

# Customer Intelligence System using classification, ensemble & clustering.
End-to-End ML Pipeline

# Library Imports
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    silhouette_score
)

from sklearn.ensemble import (
    RandomForestClassifier,
    VotingClassifier
)

from xgboost import XGBClassifier

import warnings
warnings.filterwarnings('ignore')

"""# Load Data

"""

df = pd.read_csv('Country-data.csv')
df.head()

"""# Data Overview

"""

print(df.shape)
print(df.isnull().sum())
print(df.duplicated().sum())

"""# Correlation Heatmap

"""

plt.figure(figsize=(12,8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.show()

"""# Feature Scaling

"""

X = df.drop('country', axis=1)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# K-Means Elbow Method

"""

inertia=[]
for k in range(1,11):
    km=KMeans(n_clusters=k, random_state=42, n_init=10)
    km.fit(X_scaled)
    inertia.append(km.inertia_)

plt.plot(range(1,11), inertia)
plt.show()

"""#Silhoutte Score

"""

for k in range(2,11):

    model = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = model.fit_predict(X_scaled)

    score = silhouette_score(
        X_scaled,
        labels
    )

    print(k, score)

"""# K-Means

"""

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df["KMeans_Cluster"] = kmeans.fit_predict(
    X_scaled
)

"""# DBscan"""

dbscan = DBSCAN(
    eps=1.5,
    min_samples=5
)

df["DBSCAN_Cluster"] = dbscan.fit_predict(
    X_scaled
)

"""#Cluster Profiling"""

cluster_profile = df.groupby(
    "KMeans_Cluster"
).mean(numeric_only=True)

cluster_profile

"""#Create Target"""

df["Development_Class"] = df[
    "KMeans_Cluster"
]

X = df.drop(
    [
        "country",
        "KMeans_Cluster",
        "DBSCAN_Cluster",
        "Development_Class"
    ],
    axis=1
)

y = df["Development_Class"]

"""### Prepare Data for Classification

"""

df['Development_Class']=df['KMeans_Cluster']

X=df.drop(['country','KMeans_Cluster','DBSCAN_Cluster','Development_Class'],axis=1)
y=df['Development_Class']

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y)

"""### Random Forest Classifier

"""

rf=RandomForestClassifier(n_estimators=300,max_depth=10,random_state=42)
rf.fit(X_train,y_train)
pred=rf.predict(X_test)
print('RF Accuracy:',accuracy_score(y_test,pred))

"""### XGBoost Classifier

"""

xgb=XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    random_state=42,
    eval_metric='mlogloss')
xgb.fit(X_train,y_train)
pred=xgb.predict(X_test)
print('XGB Accuracy:',accuracy_score(y_test,pred))

"""### Ensemble Classifier

"""

ensemble=VotingClassifier(
    estimators=[('rf',rf),('xgb',xgb)],
    voting='hard')
ensemble.fit(X_train,y_train)
pred=ensemble.predict(X_test)
print('Ensemble Accuracy:',accuracy_score(y_test,pred))

"""#HyperParameter Tuning XGB"""

params = {
    "n_estimators":[100,200,300],
    "max_depth":[3,5,7],
    "learning_rate":[0.01,0.05,0.1]
}

grid_xgb = GridSearchCV(
    XGBClassifier(
        eval_metric="mlogloss"
    ),
    params,
    cv=5,
    scoring="accuracy"
)

grid_xgb.fit(
    X_train,
    y_train
)

print(
    grid_xgb.best_params_
)

"""### Feature Importance

"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance":
    rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance